[package]
name = "konvert"
description = "unit converter without any dependencies"
version = "0.2.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/patrickbucher/konvert"

[dependencies]
